version: '2'
x-restart-policy: &restart-policy "no"
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    restart: *restart-policy
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
    networks:
      default:
      dns-metrics:
        aliases:
          - lancache-dns      

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: *restart-policy
#    ports:
#      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    restart: *restart-policy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
    networks:
      default:
      monolithic-metrics:
        aliases:
          - lancache-monolithic

## Metrics exporter for DNS and Monolithic
## This can be disabled, if you don't want to export metrics to prometheus
## To disable, comment out the next two services

  dns-metrics:
    image: prometheuscommunity/bind-exporter:v0.3.0
    args:
      - --web.listen-address=:9119 # This is the port the exporter will listen on
      - --bind.stats-url http://lancache-dns:8053
    ports:
      - ${METRIC_BIND_IP:-${DNS_BIND_IP}}:9119:9119
    networks:
      dns-metrics:
        aliases:
          - bind-exporter
  
  monolithic-metrics:
    image: nginx/nginx-prometheus-exporter:0.10.0
    args:
      - --nginx.scrape-uri=http://lancache-monolithic:8080/nginx_status
    ports:
      - ${METRIC_BIND_IP:-${DNS_BIND_IP}}:9113:9113
    networks:
      monolithic-metrics:
        aliases:
          - monolithic-exporter

## Network definitions, do not change these, unless you know what you are doing

networks:
  default:
  dns-metrics:
  monolithic-metrics:
